service: demo
provider:
    name: aws
    runtime: rust
    stage: ${opt:stage, 'test'}
plugins:
    - serverless-rust
package:
    individually: true
functions:
    hello:
        handler: lambda
        environment:
            AccountElasticsearchDomainEndpoint:
                Fn::ImportValue: account-${self:provider.stage}-AccountElasticsearchDomainEndpoint
custom:
    rust:
        dockerless: true